from dataclasses import dataclass, field
import mido


@dataclass(order=True)
class MidiEvent:
    event: mido.Message=field(compare=False) # Don't use this when sorting in a priority queue
    timestamp: float                         # Time.time() returns seconds as float
    from_user_input: bool = False            # If this was generated by a button press/the user
    note_for_user: bool = False              # If this is a note the user has to play
    was_hit: bool = False                    # If this note was successfuly played by the user
    play_note: bool = False                  # If false, don't send the note

    # Add time in seconds to this event's timestamp
    def addTime(self, time):
        self.timestamp += time
