name: Build Executeable

on: [push]

jobs:
  archive-linux-artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libasound2-dev
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build with Pyinstaller
        run: |
          pyinstaller src/common/main.py --clean --onefile
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: linux-executable
          path: dist/main